### ISSUE TITLE
Add html motd? :)

### ISSUE THREAD

**Issue by Pomdre** [itzg/mc-status#3]
Can you add motd html?

![image](https://user-images.githubusercontent.com/30056774/44309107-dad1d380-a3c1-11e8-89ec-d3c6b04a7643.png)
As this.

**Comment by itzg** [comment]
That seems like a great idea, but the upstream library will need to be enhanced to include the motd field. It doesn't yet exist here

https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/data/status/ServerStatusInfo.java

**Comment by itzg** [comment]
...did you find a way to get at that info and that's how you created the screenshot/image?

**Comment by itzg** [comment]
Oh...the `description` field is probably it since the `Message` type seems to be conveying that type of info.

**Comment by itzg** [comment]
Sorry for the chatter -- I'm having to refresh my memory on the code. OK, so I'm pulling the MOTD plain text already, but now I realize you'd like the HTML version of the formatted text. I'll have to look around if the library provides a way to convert from https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/data/message/MessageStyle.java to HTML.

**Comment by itzg** [comment]
An alternative to passing the HTML formatting back via the REST response would be to render it within the web page JS such as what is done here

http://jsfiddle.net/fku9gsax/12/

**Comment by Pomdre** [comment]
I know how I would like to do it in php but not java:P

**Comment by Pomdre** [comment]
The picture is taken from: [https://docs.gameapis.net/docs/mc/query](https://docs.gameapis.net/docs/mc/query)

**Comment by Pomdre** [comment]
`if (($Info = $Query->GetInfo()) !== false) {
    $hostNameHtml = str_replace("§k", "", $Info['HostName']);
    $hostNameHtml = str_replace("§l", "", $hostNameHtml);
    $hostNameHtml = str_replace("§m", "", $hostNameHtml);
    $hostNameHtml = str_replace("§n", "", $hostNameHtml);
    $hostNameHtml = str_replace("§o", "", $hostNameHtml);
    $hostNameHtml = str_replace("§r", '<font color="#">', $hostNameHtml);
    $hostNameHtml = str_replace("§0", '<font color="#000000">', $hostNameHtml);
    $hostNameHtml = str_replace("§1", '<font color="#0000AA">', $hostNameHtml);
    $hostNameHtml = str_replace("§2", '<font color="#00AA00">', $hostNameHtml);
    $hostNameHtml = str_replace("§3", '<font color="#00AAAA">', $hostNameHtml);
    $hostNameHtml = str_replace("§4", '<font color="#AA0000">', $hostNameHtml);
    $hostNameHtml = str_replace("§5", '<font color="#AA00AA">', $hostNameHtml);
    $hostNameHtml = str_replace("§6", '<font color="#FFAA00">', $hostNameHtml);
    $hostNameHtml = str_replace("§7", '<font color="#AAAAAA">', $hostNameHtml);
    $hostNameHtml = str_replace("§8", '<font color="#555555">', $hostNameHtml);
    $hostNameHtml = str_replace("§9", '<font color="#5555FF">', $hostNameHtml);
    $hostNameHtml = str_replace("§a", '<font color="#55FF55">', $hostNameHtml);
    $hostNameHtml = str_replace("§b", '<font color="#55FFFF">', $hostNameHtml);
    $hostNameHtml = str_replace("§c", '<font color="#FF5555">', $hostNameHtml);
    $hostNameHtml = str_replace("§d", '<font color="#FF55FF">', $hostNameHtml);
    $hostNameHtml = str_replace("§e", '<font color="#FFFF55">', $hostNameHtml);
    $hostNameHtml = str_replace("§f", '<font color="#FFFFFF">', $hostNameHtml);`

something like that. but in java then xD

**Comment by itzg** [comment]
Oh cool, I didn't know about gameapis.net. Trying out their API with hypixel confirms how I thought the conversion would go.

**Comment by itzg** [comment]
@Pomdre does this new `motd` section look like what you expected?

https://github.com/itzg/mc-status#formatted-motd

**Comment by Pomdre** [comment]
yes!! Thank you. I'll try it tomorrow

**Comment by Pomdre** [comment]
can you create a .jar file so i can test?

**Comment by itzg** [comment]
I am going to work on switching hosting of the jar to BinTray, but until then it looks like this link will get a build of the latest on master:

https://jitpack.io/com/github/itzg/mc-status/master-SNAPSHOT/mc-status-master-SNAPSHOT.jar

**Comment by Pomdre** [comment]
Html does not work on my server.
ip: 90.149.222.18
Port: 25565

{"host":"90.149.222.18","port":25565,"version":"BungeeCord 1.8.x-1.13.x","protocolVersion":316,"players":{"max":250,"online":1,"players":[]},"description":"","icon":"iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAkeklEQVR42m1791tUV9c2/8R7ve/3JD6JNQq2WAB7SewtGhNjFFARBWyAoiCdGWAYhgELInbsRkWNGmMJaqQrRkCaCghijb0kCpj7W2uXM6PP88O5Zs2ZfeY6e+37Xm2v7XL79m3U1taKq6GhHrkXLmH73lPYe+g0LBlH4W8pRoClAH4J+ViUXIhASyEWJhbQZ4H4XLW2CKdzC3H0VD5+OVeE2w11uHnzJmpqqrE/5wyOnTyHQ4dyMNdUhKW2Iiyg/+HnglKLMSepEuFenWBdMRpbYycifF4/WFeOw57Er9F3kA3dPdPQ3d1CVzJ6DkgXn909rOjpaUcPjxR5eaaK+z08U+g3+b0HjRGyhw1d+ybg814mtO9lhlv/JPE7P9/dPUn87nLjxg00NTVBfDY2YF/OOXjHl2CeuQiLUy5jSUqReOGl9MlXICmBJxJsL8Z8cx4WW4vgn1QMr5h8rM64gscP75Aya3C9/BpmxxbDJ44UllQiJsyKZAXy8/zcfGsVchJHwRo6HhsjJmBPwnSkrBiLnNTJ6NjTTC+bJifraSMFpNGns8wTkZPpOUDd5+/qN1ZIl142zLWuxe1Xdah4dh0e3yXAta8NPQbwc2lCgS6MgIqKCrFqjbfrsPvwBVrtIvjEXhIvy6s+Lz4P/qQElvm+f1KBUMTChAKFhkLMictDaHoRnj5qQt3NWlSWX8Hs6Hwxlp8PSJLo8Y65RIooxGJ63stciVCvzlgfNgqpwUOxzMcd6SFDkRk2AL0ZAR52uPUziRXlybPc3SNZTNCtf4JacRvJZoEMnpAbrayW27uaELdpP179/RBvWh9hxEw7un5pkWMYWTTOpbGxUcCfEXCnqQHZhy/B11woXnK+WcKerwWKAjwRTQGe0ILEfEJKkRgfYi/A2fOFOHGmAIeOnSPYFwoEsRL4WmYrhq8pT8hBjCBrNSK8OyI9fAJRYAIifYkCoWMFBfqxAgasNV5UUsAqlPEhBWzGJyukp6IAK6wrIWBmrBW51UTR8lx4TjMLBPRU1BIU4MmzEiQF6vHTSXqxBJ4ovXBqkZhAgHp5/u5HSmEIL7LKiTEtgu0lQl5C9xYSHbxj84XtYJqwsvj+MkUB/j9+nscvSqvBttVDkBHzLTaEj8NO87ewhozCfstYdCLO9hywRk1WKqAHQ91DUqCnIdsV7DUF7IoCNnF17W1Hu85mfNaVFNlfjhMU4P9jBDQ0NKCWDBbD/15zA/Yfu0QrX2jAVsBewFbCfo6iAE9qbtwlmmC+4PM8WlmBGEICG8z5pnwxnqnDz2gKiP+1SAVLCnTB2tDhSFs+EsvmeCAzfJSggDRqdrhqeDPsmQLuvPKptJImRQEH7HvS5Hh8D02H/omCMvybmzB6VvFdjpf3XZqb7+BCXgn2Hf0dx88UwZJ1mlZRQlpbfuYrr/xiq6QA00EbxAXKBixKlqvKilpsdcCex/H/8BhpUKVd4DF+RIFIr/awrxqHLUSBaN++sIR8pbwATe6/UOCLfolk1c3o0DtWIEBafZtQhPy0STuh6CA8CBtKAXtp+T+gAPN+ffY5eMUWCeO3yFoiJuqvKCDgThNlCvB9bcX5u57gMpucGH8GpUqvsSSlyKAA32cKsL0IoueWKOUF2GtwMGE01kdMppUfjc2x07AuYiL2J09El95k/IgCcoIpQgEd3ZJhOZGNxhd1+K0pD1084uk3u4JzioMaBgXshueQ9+xSUYoCAgH37zYhbfNxLCDuCmufJK29M2ylXCAUwHTQFJhDFPBXCBDGTcmMEP4vQQEay78FKkTNjcsT/+WvKBD0YydkRY7F2pVfIWiuJzLCvsaWyMEKrkQB4QWkf/+kUxR+LrmI568e4NFfzfi8bwytpE15B7nikgIpEvaCAk7eQaHJmQ4ujx7chTXzGK1OsXgxhvoiq+S+n4C6XGlePcFdDoSUMjSXtafg8ZoCvPIa6owOHrdUIUXTwTe5GmEz28G+cjQ2RY5B+JzeSAr+CrsTviIvwLxfI4McYezS0cE1ARH7N+FCTRGyS46h24BEoSQdCAkKiMlr2KcqrivYe1gcFPCQ/+tyt7kRGdmnBfz55Tlg0f6fKaAnx5APdJKFd7BIChiwt0rYC4QoCrBCmQJL6RlWLD+rvUAgUWCviSgQOQUZ5AU2RU1EGtmDA8nj8FnP9YZ11/BmuRPR4N9dk9GhG020v9URICk7ob2DAX/xbKoMnJgqggJ2BwUeP7qL9M0/kxWXMOaVYuhLqErjpmHPimFZxgMFYgxPPEDBXCAgScYPCxQaWAHzNQXMkhqMHn6OKbCCAqFNUePIDY5GkE9/bFg9Gjtih+Hz3mvFS7v2izMo4KbgLSDdz2xwWwZC6j6P8VTeQXmBHgL2kg7dlSy9DFHg6rXriLQdpBeSq+pryhertEhZfhn/FwhrvySl0IC2MGSK+4sVZbSSAiyOcfxfCxV9GCFMJbYVjAhf8gJhs9ojPWws1pMCIuYSBZYNw664gWjfmxAwcI16WZtasWQ1aWXFhe/XFLAZBlN+V4ZQ2IAPLT+jxqBAkP0KFlHMz6vFKxmkJs8XQ1jAniYYnCq9gLykdxAUoPFBNpUjkFJCGPa0+qygkDQ5eeEpUosNhYhnFQV2xY7EushvsH7VaOy2/AB7GEWFkYMoeVmvIOvwAvLFrYalF/LAdAF1mTBJLyBluyNiVB5AxP+eKSq/sAvUuISuuSxiel4Zba15YtpaByjY86QXiVj+dzFGx/ja33OMvzBJKpGDIFaC9gBMgYAPKCBjA5/EaqyY1UF6gTCigFdf8gYjcShlDPn6tWIFXZ1g79rfpPy79g42IxfQtoJzhB46QNKyhr3hHRKMeMElYkOpkaIGOsFYJz/8svp3XlWW/UlZDGfmeqAKb3ly2lX6K0XolfZXiuT/08ZycUqxiDiDv2+HHUnfwxo8AotmuGFn8gxsjxpMFFgnKKAjNrH6OhdQEDbuK5emM8ceKmHSgVB3ZUQdsl25REJA2LorBjz5ZUOUFdcpsHZ17B0YAdqSa2WIHMEIhCRNJMdlsLRAKYtlkT4rL+JP0ebS5DxKgcdjbfgkZEePxq6kGbAuH4U9puGkgA0ysVET0bG+tgdyojaZH3imGMrQtsBIkZkWmkZOQZEcqxTgS7DURo8nrkPf+WYZ5/Onr5kNWCm8oksox79Ck5fy3Hh63sypbwl5khIxWc4LZPYokeFnzjMKKRI1TDPKJYgqET5dKA8YQRQYgxDv3rAFDcWaFf3Q4cv1H0CaX1hY+/7sAWzo1kfK3d2JDn0ThNzDnb1GomEUdcDT08OmYC/p0F0ERSoXWJ1RKmP6BJm8BKqUV1d8hMuzlGBV+knsPLwNG/ZmIWP7Bmz5KRubDmzGBpK3HcxG1r4s2Ddvo+dLZeCkbICGvXOOwIhaYisRkWQYucEtCdMpHZ6MYK8+2BD7DXabR5ARXCutvQF1nmgyeo82od8EmsSIOLgNMqHroER07B+FbiR3dI9FZ88YQoVVBT9243mx8u5Wp7zCIgsijAAdsweqQEhXbnRQNI9Weev+9QDm0jUKLfeG02cAXSNIHkmfC+gagoeN3rT61yV9nOL/pTooUslVCKXP882kkKQ87DKNQdrKcUhZOgh7LDOQtvobZEd5CApICNtFlscI6OCajMzcw3jd9hBFd8qQ8PM2IV97WA3Tsa143vIAta9r4DrYLCJEnRILCgywO1WU7B9SYJ6iAL+49v0LEhiubK2v4PuIP7AmKxP4Zxpa343FXw2j0Pr6B5LH4E3jaLS++RFo+QpNdXMwM6oGXjGUV5ikO52vaKURJT1NgaCAT1w+VhMF1pHlTyT/v3xuf0qNv8bWKIoDmAIitmd428T1rw4xOFHyO+UCD3HzXj02nz6Kpy8eoPFRI/b+fhpPXtzHi9aHIkRmmrj2dc4FHHJ3lT4LCrAX8FNWfqmq/wWIhKYIKwn2Gw/sQ+qOfTi0Kwx/VQ/E8+bhePLHIDyrGCHkp2WD8bR8BF42D8HtPyYjeUsO1mTvQGLmflr9y1KZysMI96e8BVPA13QJq707Y3PCd9gYMQbLvfsiM3469pqHKwpwGYz4PDwebsMJ6v2iMXetBetOHkLY7o3wy7Bi98XTMOfsgm9GMnbknoTt1G58MTAOn/WOQ0dKlqS7s6qwWNGJvYumQPj6UgF1zfdgRYG58aXYfzSVoO0joP733a/wD0Lw/t0UPL89Qcj/vJtM8iSSV+D924l4fW+KosYQ3G0KpAlWGAUTTQFNB/YCS8gLbFo9HNsts2FfNhDZ5unIiJ6GbRGaAqlo72rF9qJjeEVQP11biESa7L0nzfi1ogTmQztx588mnK/5A7Fkk+ofNOB8VSnCDmzA/ddN+ONJGboNpVDa3f5Rmqy8ACuAEeCrqjT8gr4mdldX8ENUObK2pxHspxLUx+FNHcH+7Sy0sdwwGm1vvelSFGD579GkpLFo/cub6DASN2oWYEZEFRm6YlJmkQynE6RxDBRldso34gsQ5t1F1AKYAiFz3GEPGUaU6G94gU86RlP2V4gXbx6ivLEaB/JO4/lrosD9OuQU5SoKNGH3hVNCbnhwG1lMjZcPhE3oPDAWbn2ZAsoYOuUFrAyXSFLAfAVLf7L2keuPYNO+rcjcvxO//LQYb2+PwKtHX+MZwf551Ug8vzMMT64OJNgPJ3konpQNIhoMwzOSn5UPwNM/huBV82DUXJ6O6HUnYN28H1HpB4gGJSLMlikzB0VkJ+J+R7RPJ2TEfousiFFY4dMXWabp2J8wTIXCaZT9JSFoUwayz5xD+PbtCFi7BjtOn0P0zl1YkJGCzFOHYTq4AwEb7dh/6Sysx/Zi3rpkUtQ5rDv3k6BDO9d4dOiVoAIpmwqQLAIJLqvYC6TKmH+e6SqO/ZpEEPYS1v6v5q/xHsEE+8kK9gT1d5PwonkKySvF/Vf3p9IYKT9rnEz3QwVNXt0eT//hT9dwPGr0wvyESuERlhl7ChQQWfOFF9iV7IX04CHIip6CLabvsSNqACEg00hcOndPJioko1P3FLqsaO+Wgv/9NBHppw+i8c9GnLxWhNV7t6DhYSN+LS9GSPYGVDRU4+fSPCzblYa6ZzdRcP8yeo0xUTzgXB2ysQ24gjmxDMcSsuDl2LmXFTANbS0TCPZf06e3gP1rhn2LD8GdvEDTGJLnSArcpvvv5kpZUEPdbyL57zlEh69xt8FH0ME7tkhQjG0M24A58flYRXHAOkqEkoOHY6l3fzKGY5GxiimQoeJ/s1H2FjG/yvQ+6RiJ3KpCQYfKJkqqLvyCZy8fou5+PTb+ekRQoPlxM9aeOEj3H+BFy0P0GpVAgZJV7BA5eYEyrEo7irXZu8na/4Rf9gXgzc0hZOFH4MmVAXhW9bWQn14bjBc3RuPlA4L+NYJ6GY25MwRPr3rSb0OIAuQNrg3Ek9KB4v6z8kF4ctmTvMMg1F+bjBDrGUSvPYLw1BwyjCUUUpNtIArEz++GLLL8GyNGI9T7S2yI+Qb7Eobi855rPtwOU7KICsmKMzVCd27E4fwLSD68D/6ZNrIDv8B6dC/8N6bi+OXfsf50DnyJDj+TnF1wHK5DTPi0SyI+d2VFyGjRZVnqdZw5H0OrPpuusXjTPEpa+5apCurLJaQF1FcI+VnjBEEB4QUaWF4lxj9rmCgp0DKd5ClK/hYvyVPIYGkkXj/4jla+UlSel6XkUy4wDtlJM2FbMoAiwhlEgRnYGsFxwAZV57Mbsb2s9qSoFDhFUONz8hL/92kSYg9ko/ruTRwquYilW9eh6s4N/PwHGV1STCF5iYNF5+G3JQkV96/j4p1C9J1sJuNolQo4dCiCXm66gP3r+tH00l4kjyeoj0Vb6xxp+RnqrQz1sXjN1GidJ6D+moKitlZfgjvJgg7z5JhGpsNcSR+iw/u384C3ZEzv/4AfoypEJDiHvEDwjM+wOWo8UigfCPLuJ6pDG8M9RDYoKZCgdnpsjrxApMPxRq7/aacoHCv+XdChjlyhpsCdP+9gzfGfBAXuPbmLtJ8PCJq8bnmEAd9YKZ9Igkvo+hocyF6Bv+s8CerDBGyfVg0X8tMSdzytlPKTEg88qxwhKPCUvMCLqmF4eX+oogB5iDsUHDE1Sj0FBZ5XMAXc6dmheF45GE+K+uPV3YFovj4GPvFVZHS5Cn0Jq2Z3wub4acgK/wqhPn2wLmIC9pmHyoqQSnU/qAgpCnC5SxdLOxIdVhEdTpfnI/PcUSzalIafiy9gx8VTWLjBhnNlxdh16TQFS1b8RkYy549c9J3AEaZdIuDExVQRwLxv/Q6vHkyVsCfoPtOWv2UaQXq8AWmWheVnuX4Cyep+/UQl0/j6KYoyRI36qcKboGUKHtTPoeyxiowgBV22AjJ4g7HTMgvWJYOwhRSxOf47Co4Go0OfTKd6vu3DAunAjytFdrIJFnzWNRn/1y4JwZs24kpdBfYT7OdvSMHlmxU4UJgLn7WJOE20+OnKGXw53izCZZfFKZW4eHYJKeB7gj1Fc7fI9bV6Cwq8rhslYf9uvKBGW5uCdz3db5tPsB8rKdDmR/fHSQq0+EpqNCo6MDXYa5CnwN9fEQVmkDeoJG9QIHKByHndsDVmAuyhIykb7EtZ4XikrxiBDooCzrvAGvZG/d8oiurKjw3tOkdj97lzYu+g+fEdpBMFOEC6S9GjXVHglUGBZKbADZzZN4csv6eA65NChv1QaeGLPPD0Ostk4ZkCLFPMzzR5UcN0GCo8wnOy+C/uD8GL8oEUMNFv98hjVBIlrkr5ZTV5hVIPvL4/EPeqx2J2TCWFxyWCAlE+nbE+ciJsIcMRu8AT9rBxFAkONyggoK4oIMtaNoEAsc1lFEUt6NwjGe26JeJ/28VhaWYGTl69hB3nf8HiTekorL2Gw0SJheQdWD5dlS8o4KoRkH95NSFgMd63zcBTAXWCbtsPJI+TsG+dQTAeL4Of1u+F7KDARAH11r++wdO6iWh7H4zWv6fi6a1JJAdJ+eY34v4/b6fg3i0fzKWUmbNB9gLZpvHYlvAD0oKGYHviDKLAdNgoNe4oKOCoBvXQsbyyAXrXmO936m5DTM5mVDwg2F89Df+sVFyqLCUb8Cvmrrfg4vUr2J13Ft5rEnGcFLGr8CRRwCQpsIgUcEFQYDr+aRsngp/3rT7SIzAF2pgC0ju0vZ8v6cABD1t+svCvtMx0uD1GUYMpMEZQ4/1fY6QXIBlvR+LFw+8wM7JC7EPMiz6OlbM7Y0f8ZMoFhoqi6La4iSImaM/7AqqA6aj5f1Tk9JT323WOwZHCCyJNZi+Q+WsOnhPUORBKF17gEe6SnHpsn6LAQwcFwjfW4siOhfjzxhjca5qIRwWDKeYnSN8l2Be5k+UnON8dIijwtGKAlK8QHcjKv3hA1r6MPcIgvHxIUK8YKKDP8quqwYISr0h+fWMg3lR5ou25J+7cmEY2oAKLU67AJ/ww4n3JBpimImXZIKz26YU1YWOwM24sPu+1zlG/N7yAxanHx4KOFAO0+yIZ//P/4hCxeysuXC/B5t+OY8nmNThP2eKevDNCvlR5GaeuFSJk91o0vWhA2ZNyuE9JhGtflQ0uTK7AD7Qq34bV49TFBEGHttaZBOlxAt5tLUSNOob9cpK/w7M6tvwhJE8nqE+Q9999iyc3J6ClJQgtrybjCVGgpYXyiL8moKZsMaaG38Gs6Cpa+UpRFA1ILkFwws+UAk/EZgp+bEsGYgcFRFlx05G8aIBBAcfurs0J9pwkpcB0fAuKG0qx8UIOAjen4der+VhDyRG7O7b2mWePCdj/erUA2QT7zgOi8e+e8RRkmWRixMnQivQSsRvEpa9Z0Vdx6pdVwiO8b6VcgKz9e84FmA4C6nMkHVhu86XghijAlp+9AFHgFcP+H3+0Eezf3BsvZLwdgeraEMyOLpN7DRbVKGEqwtzoEwid1Rk7TVNgC/0Ky2b3ITpMQtrKr4UXEGGwMnaiscGpsPlJpxicrcgXQU757RrsyD0hcwGmwCmmwCNBgbTjB4T8/B3lAqNp1ftwUdWxTeYStfGq6PQQGxzWchzNXkRJDdHg0Sg8KyHI1wwka09Qv+yB59WDpUwW/XnNUCmTF3h1azhePx6Cl5Uk0xiW39X2A273IQV0R035LJpwhUi5RU8RV4eIArNCDyJpgSs2xX8DC9mA1XP7ID10BLKixshIUNX1O3QjC98lCe3JynekrPCzrlb8z7/ikHJiL0pulmPr+ZNYvXszikneQ8Zu+Y4NQj5UfB7h+zfgxuNqXP3zKnqPSSAlqv0CVR5z4dY2WRGSKAi0VWBG5HVMX12Pw7+mipS29e/vCd7jaKVDSP5OQL2tbTnJ34qYv7V1OVr+mobnTVPx7h1Z+9djkHshHlPCGglVNeTvy8U+gt5DlDvNJViedJwoMAmb46Yhbn5f7LDMpHxgJsz+7pIC9IKdyL2tO78fFyuLYT6SLbbHcyuKYDm2B4sI9kcKz8N0aCf8KOBhOfnYXsxdZ0EOBT4ZuYfQyT0S7dwoAerBZfRkR2VIxBZ2SQHeyhJdYaKeL4uXs6JLkXMslhQwg2gwXlj49wL2JDeTAt77CQq8ucfyQgn7ZlLSPwEU8Y3AldJQgv01o93OX+0m6xY73mfwiz2JUK+u2J8wBUnBI7B0Vh/sNk9BGgVFXBHiGOCTLjEou18m4J1bUYxT5N+fv3qE4hvXcCj/nLhffrsa28n4sXzrfgMyfjkk5GeiIhSD7v24iSLBafss0agVukRlEgVUSYyRME/t4y1MLsPhHUHAw/5oeUGW/Q8PvLxJ1v3PIVK+MVTIr665kzwMb54Nw7vKL4EHBPt/uuLaFT+CuyyR656iAKUIpsCSlMvwWnVIUGDd6rEE/ZGImEfJUPxUbFw9Qm6NkeX/3NWEI9WncedlA7blH0M65ffXm2oF7JOO7BHynvyziPtph5BzKPU1HdmKJhpf8qgUrsNMYvOku7IdRmyhXKvwArrbQ+wFGA0OBFeiw/erKzE9vAE5Z9KA9wF495pS3duT0fI2iORv8fjmeLQQ7PF2Ik6cNBF1bmIOubn5CVfFNpruBtE7ypICRVhoKUFI0glsj5+AnUk/IMa3LwVCPyCLcgGToMAG1RZnR2cKgbnK++kXJqzav17U/1buzMRCUQM4hdV7N8sK8flTSDqZjQ79I2l8AuUTJmFERb6gG6YMCsgmCpflRAHdDOGrWt38Vf2eV4+vmZGlOH0mQpTK3lMg9Irp8M9CosBYJRPsW4fjUkEUUecP0TWq22T0noPcQf7d6CjzjiVkxJ3ESq8vcDBlJhKDhmPJrC+x1zJdoIErQrLBgcvXacJy/6tjLArqS/CMKFBUW4aDtPIc5JSRF9AUePDmDj7vEy1KX64C9qmOIMqQP6KArgrzyuiipUMugJ+lAr8doHz+aU/gHUG80pWg3l/KNd1JdifluCEvLxgLksoFxNm1cu2P4a8poBXKvy9SFLAGdMf6iIkiAYr390RWDEWC4SMlBTwdgVAvkv/dxYwjVWfw+O1d5JTlYvPFI0I+VZ2HzNyD+JPk0sfX0Fl0jzmlz56aAjanRgqbokBGqdoO0zu/juZoPQHR3GRlz1AJr9haeJtv4PuISlrFGnibbpDXqCJLX0uwLzMaKkQjheK9/s5UWJQsPwOtlxFMFNgcMw6ZkeMRM78fdlq9SQGTYArwQKc+G40dYBEAMXTdU9HFMxbt+8eJSXZxj0UHdxNZevrePxodPMzo5BFL4yyiy7SHAXuVPrs7eopkVZgpkFYi+3l0z0+S3sLKN1ZM9g7J7TK5dSa3xnnMEtU/4BX9u+gWEY0PBHXdZc6w15uiRgO2lZurJQXCfboix/4jzEuGYvGPX+JA8ndIpcywY9+NBGGz3PdXWaFsdOTdIgv9liRa5LhRyo1kVg5vnzFVZPfIx7D/b7JV7g3qnWGj0cEi22N0WysriVPXQCXPjb9ktMvwmGXGJmqeMKKBwqXmC4UEGu12mgL5AnG8BzF75UGsC+4L+6qxWEcBUFzgEEqNJ2BT5NeiQ8S5EaKX0dqmmh08ZINDL7XTK2Rjy8u5gmQzJqvhb/Qa6a2xQHUQQlts0dRslR2guhs0yKmJYplzK51T+xxPeKlqntJwF5C3OmTjGWsJQq2/IHnFKJzauACx83sjdtlYnMj0g3lhH/ICG42mB+PMgKdji8v5HIHMEWz/0VPkaLFLVwmU+j+1LcafLqvWXhGrrhsYGOaBKijySygweoPF/eTCD+jAHR8s8/O6v8joElX/p3uNnM8aMCV8iAKcC8T7uWFtyFAkBI1ApN8AbI0eCzvlBR0oHXaj1ZQWW3Z+OdrkrKqJWleKTMZpEVejTU5VkDyd2uo+aqUTXiCcQmE/px4g3ePnTIEgJeujLjzZBYkFqu0l3zBsrBCx8lZJAf4PfdxGnxsQm7BW2XThE56D6LldsSluCuzE+0g/T2SSEVy/SkaCusFBrn6ao+XNSJNTP4A6V4rcdKVogEM2jJ5uoPTQXaU26QU0n3WDhDZazHd9TohDZk5kRIMD3dfujJsdZPeH3FnW3eVMH00Dlvk/tCcQHWfkBldQLrA1brwIhMwLPSgP+AHZiTOQGDgAnfpmGRToZTRD2z8KZBTUlUtjGyBlqwP2HskG7OX/ORqlRTosXJ2igK/KBXSHp+4Z8jPnG/fnaQo4e4dEDfsiseXlkOVRGh7DwZWmAFNiThz9FnWc3J8btkSMhnnZcKya54GdFBnGL5lINmCd3MISq5giVlD2/KiKkHP7nG6o5l4go4NUUsMR/5v/ey4Qtv6K6ueXbS16p1jDnldQ5AhKXqbkhUl6fJ5qlSuGV8QZ/LjyGGZH5mJG2Bn4ROfix9Vnxfcge4nwALqzbGHSZcwL2wNLQE9kRk9CrP8AxNG1KXYCRYWT0PHLtcbBJrlD5NTsrAukigLOxdIPOkvdkw3Y6/S3h6dTNuicCwi4WgoMq86TYqjr/j7dBM1jDQqQzKG0iA8SCnHst0o8uFOL5sZaPGiuw+26Kjy+X4/TuZxkSeMn2u2YbilXEGv7CVvjJ2JL/LdIoChwa+JMbDNPR6j3IHTpl2WUwB3tbzajy1N+d6aAVVJANUPJQMi5g3SNo4NUK4cDIeat7gvShi7QohuepRdgg8Y00d2hOmUW+YI4RFWIWVF52H2iErfrb+D69euor69HVVUVaqqv45eL1RQQ5clASB+jiSeqhGUjZiEFP0nfIjJgAELnumOPeRIsIVMUBRIdFSH6dDPkZKPbU/f/6KjRKJaKrbTEjyigAiFBjVTVJWZQoNDRCaoaI33N6oRXqoS6v4oB5itlsN/3ijyHH8NO4vvQk8jaX4SmRlp5dRSPP+/euY3dx0oxO6aQkqpLpEAZCC1MugLvoExYA3siI2I8kpcOFRTYFj8J9hWThBvUDc7/SQElc46gi6V03wiEVHzwAQUML6CrQSoQ4g4RhiQHK7rtlUPdxQL2kgIfw577i1lRvMF5qeg6blRdwa3acjF5XnU+iCUOY9XWCiXU36pFZVkJmurK8WtuqTiWt4goEGU9iO3myciMmkwU8MA2yyxkxX6Dld6DiQIbVWOz82HI1A+6QMXvA9cYkZ4j5k82nun+gWxxygXkfRdeDYa4poAOigTsFRrm67yA8wVl4Rn2vKJnLtWgof6mgH1dXZ2YNK/+rVu3UFNTg7KyMnEylWWmQ25BDVGB6BBXBN+wHYhZ0BsHKAWOWTwMy336kTwVUYHjyQ2uN468sBLkSS+LQQe90lJOMiZr+H6jKTr1PyngJAsK6DKVbnRm96X7fwPUIakFidIeMAVmrj4Pr6jzmBGeiyNny4n3t8TZQ159njivemVlpVAII0HbhNsNt5Bz+hpmER18TKX4LjATqUv6EORHIiV4OEyBgygzHA1r8EQKhNY6NUKnOBUyP4rnldzJzYrPuyWjg2uikUE66JD+0VkBq5Eau0RllqoWOXVIUhUsltpkQKQVsFSlyXy05reLJSgvzcN1gvXNG9Vi1XmCrASeOE9aK4FlVgQjgOUbtdW4drUEJcUFOPvzTmyMJgpQAhTr5y4KotsTpiHEa4iggF59GdDYHImNbpT2TFGNVFaE7c3C4byLMB/NRpfeidILeNjExHsNXOOggNpZ1nRwWSoMX4FxQNJfNUrKI66yVKbPBYhiadQlXCiqEafEq6urxcT51CnDXlOgvLxcKIAn/bHMSuJzyjdu3ML5c8cR9GM35KTORMTCQVg+px+O2KYjwn8sUWCDOg0mj8q6qdRY7gYnGjLD/tPO8bhUV4Rnrx6g+nEV/t2drLx7ihErfJAC691kpUhKhi4bvl6HvfJ4S6HhEoOUqwxIkl3eZ/PI0NU7oM4Tam5uFhPUFOAJs6zdIX+yghwIacKJI3sp7O1HRnACbMHDkLiY0+HxSF/5jdgb7KkCGKPfXwUzzvE/ewGuFGUXnhAV4aMV59G+R4Jh6HSvsKbDB16Avv9/5NfQyYMSr1QAAAAASUVORK5CYII=","motd":{"raw":"","html":"","stripped":""}}

**Comment by itzg** [comment]
Hmm, the response content is self-consistent at least since `description` and `motd.raw` are the direct value obtained from the server status and they're both empty strings. I'll try to think of a way to cross-check/debug the scenario. Can you also double check `motd` is set in your `server.properties`?

**Comment by itzg** [comment]
For comparison you could use the [mcstatus](https://github.com/Dinnerbone/mcstatus) tool (I guess wasn't too original with my project's name :) ), running `mcstatus 90.149.222.18 status`.

**Comment by Pomdre** [comment]
I get the correct text from them..

**Comment by itzg** [comment]
What version and type of Minecraft server are you running? I would like to see if I can re-create your scenario.

**Comment by Pomdre** [comment]
I am using bungeecord

**Comment by Pomdre** [comment]
1.12.2

**Comment by itzg** [comment]
I just pushed an update that upgrades the MCProtocolLib to 1.12.2-2, so let's see if that version works better with bungeecord. 

Please use this link to download this updated version:
https://jitpack.io/com/github/itzg/mc-status/master-1.2.0-gd055fcc-7/mc-status-master-1.2.0-gd055fcc-7.jar

**Comment by Pomdre** [comment]
Still not working. Has BungeeCord-spigodt

**Comment by itzg** [comment]
@Pomdre I finally got a chance to test this against a bungeecord instance was able to recreate and solve what you were encountering. This copy should fix it for you:

https://jitpack.io/com/github/itzg/mc-status/master-1.2.0-gd7fe44d-8/mc-status-master-1.2.0-gd7fe44d-8.jar

**Comment by Pomdre** [comment]
It still does not work completely :( 
You can test with my server 90.149.22.18 

[test server 90.149.22.18.txt](https://github.com/itzg/mc-status/files/2324545/test.server.90.149.22.18.txt)

**Comment by itzg** [comment]
Bummer, I was hoping that was going to be the fix for you. Thanks, having the specific server IP to debug against will be great.

**Comment by itzg** [comment]
Aha, I see what has done. Bungeecord seems to pre-parse the text formatting and returns the pieces. I'll have to add similar HTML conversion logic that it appears in the `extra` field here:

![image](https://user-images.githubusercontent.com/988985/44695404-a2bd3700-aa38-11e8-97bb-98eff038cb5b.png)

**Comment by itzg** [comment]
I might finally have it...this new version

https://jitpack.io/com/github/itzg/mc-status/master-1.2.0-g1e465dc-9/mc-status-master-1.2.0-g1e465dc-9.jar

formats your MOTD content as:

```
<span style=\"color:#FFFF55;\"><span style=\"font-weight:bold;\">Dag</span></span><span style=\"color:#FFFF55;\"><span style=\"font-weight:bold;\"> </span></span><span style=\"color:#55FF55;\"><span style=\"font-weight:bold;\">& </span></span><span style=\"color:#5555FF;\"><span style=\"font-weight:bold;\">Natt</span></span><span style=\"color:#FFFFFF;\">                                                     En offisiell server for </span><span style=\"color:#00AA00;\">Level Up Community</span><span style=\"color:#FFFFFF;\">.</span>
```

I couldn't do an exact comparison with gameapis' result since they didn't seem to follow the [formatting code documented here](https://minecraft.gamepedia.com/Formatting_codes).

**Comment by Pomdre** [comment]
Thank you now, it looks like everything works

**Comment by Pomdre** [comment]
I think some of the colors are wrong in html
